# LilChunks Configuration

# Debug mode - enables additional logging
debug: false

# Chunk generation settings
chunk-generation:
  # Maximum chunks to generate per tick
  chunks-per-tick: 4
  
  # Whether to use async chunk generation (1.17+)
  use-async: true
  
  # Whether to generate structures
  generate-structures: true
  
  # Whether to generate caves
  generate-caves: true
  
  # Whether to generate features (trees, ores, etc.)
  generate-features: true

# World settings
world-settings:
  # Default world height (1.17+)
  min-height: -64
  max-height: 320
  
  # Whether to respect world-specific height settings
  respect-world-height: true

# Performance settings
performance:
  # Maximum memory usage in MB (0 for unlimited)
  max-memory-usage: 0
  
  # Whether to use parallel chunk generation
  use-parallel: true
  
  # Number of threads to use for chunk generation (0 for auto)
  thread-count: 0

# Logging settings
logging:
  # Whether to log chunk generation progress
  log-progress: true
  
  # Progress update interval in seconds
  progress-interval: 5
  
  # Whether to log detailed chunk information
  detailed-logs: false 