name: LilChunks
version: '${project.version}'
main: org.hydr4.lilchunks.LilChunks
api-version: '1.20'
authors: [hydr4]
description: A modern and efficient Chunk Pregenerator for Minecraft
website: https://github.com/hydr4/LilChunks

commands:
  lilchunks:
    description: Main command for LilChunks plugin
    usage: /<command> [subcommand]
    aliases: [lc, chunks]

permissions:
  lilchunks.admin:
    description: Gives access to all LilChunks commands
    default: op
  lilchunks.use:
    description: Allows using basic LilChunks commands
    default: true 